cloud:
  aws:
    credentials:
      access-key: AKIAYIVDFW47QZ5FAHGN
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: cdac-app-final


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

#server:
#  port: 9090